[package]
name = "lambxekutor_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
lambxekutor_lib = { workspace = true }
